### ISSUE TITLE
Unreadable: susy

### ISSUE THREAD

**Issue by ijy** [oddbird/susy#21]
I've installed the compass-susy-plugin gem successfully and included it in my config.rb file (require 'susy') but when I import susy into my base stylesheet I get the following error:

error sass/screen.scss (Line 9: File to import not found or unreadable: susy.

If I then try including the container mixin it says it's undefined—as it's not loading susy.

**Comment by DeivisonMaster** [comment]
Pessoal, instalei o Ruby, instalei a gem: sass para compilar meu css, ate ai ok, acontece que quero usar o susy framework, com o seguinte comando: sass --watch estilo.scss:estilo.css -r susy no qual falo pro sass 'assistir' as alterações nos arquivos css e indico a inicialização do susy no terminal para uso, acontece que a importação: @import "susy" para 'chamar' o framework, não funciona...

**Comment by HugoGiraudel** [comment]
@DeivisonMaster You will have to speak English here. :)

**Comment by DeivisonMaster** [comment]
@HugoGiraudel Sorry

**Comment by ericam** [comment]
@DeivisonMaster best I can translate that, you're having trouble loading Susy in a Ruby environment? I think `-r susy` might be from Compass, and not something Sass does internally? But I am not an expert on Sass load paths or ruby rems.

**Comment by elharony** [comment]
I forgot to run `bower install`, hope it help someone! 😄

**Comment by elharony** [comment]
I noticed that the project I was working on is using `bower`, and I forgot to run `bower install`, hope it help someone! 😄
