### ISSUE TITLE
To center block with susy

### ISSUE THREAD

**Issue by artemhp** [oddbird/susy#210]
Hello, is it possible to center block inside another block with methods of grid system? or it is wrong as concept?

Example:

.block1 {
    @include span-columns(24);
        .block2 {
            @include span-columns(15);
        }
}

Inside block1 will be just block2 and I would like to center it.
I can make code loooks like this:

.block1  {
        @include span-columns(24);
        .block2{
            @include span-columns(15);
            display:block;
            margin:0 auto;
            float:none;
        }
}

but it is not beautiful. Help me please to analyze and to make good solution. Thanks.

**Comment by gamsim** [comment]
Assuming your grid is 24 columns wide:

.block1 {
@include span-columns(24);
.block2{
@include span-columns(last 16);
@include squish(4);
}
}

**Comment by Janking** [comment]
when I use :

.block2 {
  width: columns(2,6); 
  margin: 0 auto;
}

the css output:
 .block2{
    width: columns(2, 6);
    margin: 0 auto;
}

it use cloumn for  compass function;

**Comment by ericam** [comment]
That's right. Susy hasn't had a `columns` mixin since pre-1.0. If you are using Susy One, you need `span-columns`. If you are using Susy Two, you need `span`.

**Comment by AlexisFinn** [comment]
How about a simple mixin to center a block:

Where $elementColumns is the number of columns of the element you wish to be centered.

@mixin center ($elementColumns) {
        $margin: (susy-get(columns) - $elementColumns)/2;
        margin-left: span($margin wide of susy-get(columns));
}

.block1 {
width: span(4 of 12);
@include center(4);
}

This could be improved upont to account for nested context and different layouts.

**Comment by luxwan13** [comment]
I think you can do the following:
.block2{
@include span(15 of 24);
@include push(4.5);
}
