### ISSUE TITLE
Question regarding remove-omega

### ISSUE THREAD

**Issue by egstad** [oddbird/susy#283]
When using Susy's `at-breakpoint` mixin, I've run into a curious difficulty that you may be able to (hopefully easily) help with.

To illustrate an example, let's say that I start off with the following code:

```
.example {
    @include span-columns(1);

    // margin: 0, float: right;
    &:nth-child(2n) { @include omega; }

    @include at-breakpoint(30em 4) {
        @include span-columns(1, 4);
        &:nth-child(4n) { @include omega; }

        // float and margins replaced
        &:nth-child(2n) { @include remove-omega; }
    }
}
```

All that is fine and good. **Note that I reinstated the margins and float to `nth-child(2n)`.**  Then I decide to add another media query that looks something like:

```
@include at-breakpoint($tablet 6) {
    @include span-columns(1, 6);
    &:nth-child(4n) { @include remove-omega; }
    &:nth-child(6n) { @include omega; }
}
```

Here is where I run into the problem. The above media-query partly works, however, where it falls short is that it doesn't cary over the `&:nth-child(2n) { @include remove-omega; }`– instead, it only removes the `4n`. So by the end of my media queries, my code looks something like this:

```
@include at-breakpoint($huge 12) {
    @include span-columns(1, 12);
        &:nth-child(2n) { @include remove-omega; }
        &:nth-child(4n) { @include remove-omega; }
        &:nth-child(6n) { @include remove-omega; }
        &:nth-child(8n) { @include remove-omega; }
        &:nth-child(12n) { @include omega; }
}
```

My question here is this: **Is there a way to use the `remove-omega` function without having to repeat myself time and time again?**

**Comment by landitus** [comment]
Is there a good way to reset the "last" mixin? Is there a better way to change the column count between breakpoints? I can't figure out wether I'm missing something but I'm in the need to reset the column count in order to get proper gutters. Or maybe my approach is wrong?

```
@include susy-breakpoint(#{map-get($breakpoints, "small")}, $susy) {
    	@include span(6 of 12);
		&:nth-child(2n) {
			@include last;
		}
  	}
	@include breakpoint(#{map-get($breakpoints, "medium")}, $susy) {
    	@include span(3 of 12);
    	&:nth-child(2n) {
			@include remove-last;
		}
		&:nth-child(4n) {
			@include last;
		}
  	}
```

**Comment by ericam** [comment]
We don't have a built-in reset for last, but I think any of the solutions above would work for you. Rather than using `span` and `last`, you can have susy automate this with `gallery` (the replacement for `isolate-grid`).

```scss
@include susy-breakpoint(map-get($breakpoints, "small")) {
  @include gallery(6 of 12);
}
@include breakpoint(map-get($breakpoints, "medium")) {
  @include gallery(3 of 12);
}
```

That should do it. 

As a side note: you don't need `#{}` interpolation to pass a function as an argument - and you don't need to pass in a layout (`$susy`) if it isn't changing from the global layout.

**Comment by ericam** [comment]
If you do want to do it manually for some reason, I recommend using contained media-queries (both min and max width) — so things automatically reset at the new sizes.

**Comment by landitus** [comment]
It works perfect and it's cleaner. Thank you!
