### ISSUE TITLE
Susy without compass

### ISSUE THREAD

**Issue by jamalsoueidan** [oddbird/susy#287]
How to use Susy without compass, I see it depend on compass?

When I try to import it in my application.sass

@import 'susy'

**Comment by tpronschinske** [comment]
I installed the newest version of suzy in my project but im getting an error. How can i remove compass from the suzy system entirely so i dont get these errors.

file to import not found or unreadable: compass/typography/vertical_rhythm
Current dir: C:/Projects/GitLab/zui-core/layout/susy/susy/language/susyone/ on line 5:9 of C:/Projects/GitLab/zui-core/layout/susy/susy/language/susyone/_functions.scss
C:\Projects\GitLab\zui-core\layout\susy\_susyone.scss

**Comment by mirisuzanne** [comment]
Susy One does still require Compass. In order to remove Compass from your system entirely, you would have to upgrade to Susy Two by changing your import from `susyone` to `susy`, and following the [upgrade documentation](http://susydocs.oddbird.net/en/latest/upgrade/).

**Comment by tpronschinske** [comment]
I have Suzy 2.2.7 installed. I've never used the 1.x versions. I ran the project through prepros for my compiler and i got that message

**Comment by mirisuzanne** [comment]
The `Susy One` syntax is still available inside the Susy `2.x` package, and your error message mentions it: `susy/language/susyone/`. If you are importing the `language/susyone` file anywhere in your code, you are using Susy One, no matter what version of the package you have installed.

**Comment by tpronschinske** [comment]
Thanks. Just had to remove the import of susyone and it now compiles without error.
