### ISSUE TITLE
Doesn't work without Compass

### ISSUE THREAD

**Issue by adriantoine** [oddbird/susy#327]
Hello!

I just tried to use Susy without compass, first using Grunt having pretty much the same options as on the "getting started" tutorial http://susydocs.oddbird.net/en/latest/install/ :

``` javascript
    sass: {
        dist: {
            options: {
                style: 'expanded',
                require: 'susy'
            },
            files: {
                '<%= dirs.css %>/screen.css': '<%= dirs.scss %>/screen.scss'
            }
        }
    },
```

Then `grunt sass:dist` returns this error:

```
Syntax error: File to import not found or unreadable: susy.
              Load path: c:/Users/a.antoine/Git/flashcards (DEPRECATED)
        on line 4 of assets\sass\_base.scss
        from line 4 of ./assets/sass/screen.scss
  Use --trace for backtrace.
```

pointing on my Sass line `@import "susy";`.

It was working when I used Compass.

I tried using sass command lines:
`sass ./assets/sass/screen.scss ./public/css/screen.css --require susy`
And I get the exact same error.

Is there any way to import susy without using the Compass compiler?

**Comment by anevaude** [comment]
Just came here to say that I had the same issue and Laurienicholas' comment about "

'~/.rvm/gems/ruby-2.1.1@global/gems/susy-2.1.1/lib/susy.rb but what you need is the directory of the sass files which lives on the same level as lib."

Resolved my issue. Mac OS Yosemite.
