### ISSUE TITLE
Overriding last() mixin at min-width breakpoints

### ISSUE THREAD

**Issue by mrdavefoy** [oddbird/susy#328]
I'm using Susy 2. I'm using min-width breakpoints. I have a layout that spans full 12 cols at 'small' screen (default), 6 out of 12 cols at 'medium' screen and 3 out of 12 cols at 'large' screen.

At the medium screen breakpoint, I have an nth-child rule with the 'last' mixin, removing the right hand margin from every 2nd column, so to display 2 cols side-by-side:

``` scss
&:nth-child(2n) {
  @include last;
}
```

At the large screen breakpoint, I have another nth-child rule, removing right-hand margin on every 4th column, to display 4 cols side-by-side:

``` scss
&:nth-child(4n) {
  @include last;
}
```

I'm sure you can see the problem. At large screen, 'last' is being applied to 2n AND 4n. The last-child(2n) rule isn't overridden by the following last-child(4n) rule.

I can of course use max-width breakpoints instead to avoid this, but using that method feels counter-intuitive to me. I'd really love to nail being able to use min-width breakpoints if I can. Just wondering if there's a solution?

Thanks.

**Comment by Onotoley** [comment]
Here's my particular case on this. I had multiple breakpoints, say, mobile, tablet and desktop, I applied the last solution (with "&, &:nth-child(2n)"),

```
.block {
  @include span(6 of 12);
   
  &:nth-child(2n) {
    @include omega;
  }

  @include susy-media (tablet) {
    &, &:nth-child(2n) {
      @include span(3 of 12);
    }

    &:nth-child(4n) {
      @include omega;
    }
  }
    
  @include susy-media(desktop) {      
    &, &:nth-child(4n) {
      @include span(5 of 25);
    }

    &:nth-child(5n) {
      @include omega;
    }
  }
}
```

In this case - on desktop - it makes my nth-child(2n) be smaller and incorrectly positioned on desktop. To fix this I have to do something like this for desktop: 
```
@include susy-media(desktop) {      
    &, &:nth-child(2n), &:nth-child(4n) {
        @include span(5 of 25);
}
``` 

What if I have more than 3 breakpoints? The code will be too long for that. Will that be possible to optimize the "mobile first" practices in future versions of susy?

**Comment by zellwk** [comment]
Use a combination of min-width and max-width queries. http://zellwk.com/blog/how-to-write-mobile-first-css/
