### ISSUE TITLE
Rails 4 Susy 2 Incompatible

### ISSUE THREAD

**Issue by axebox** [oddbird/susy#339]
I've got a brand new Rails 4 project and when I add gem 'susy', '>= 2.1.2' I get this:

Bundler could not find compatible versions for gem "sass":
  In snapshot (Gemfile.lock):
    sass (3.2.19)

  In Gemfile:
    susy (>= 2.1.2) ruby depends on
      sass (~> 3.3.0) ruby

I don't think susy 2.1.2 is compatible with Rails 4?

**Comment by Tibicenas** [comment]
@trev one question, is it necessary add require 'susy' to the application.rb file ? because with the rails/all suppose to add all the gems listed in the gemfile right ?
