### ISSUE TITLE
Variable conflict

### ISSUE THREAD

**Issue by 0nn0** [oddbird/susy#398]
New to Susy. Couldn't get the debug grid to function properly. Finally figured out that I had conflicting variables, to be specific `$base-line-height: 1.5;` which caused the debug-grid to malfunction. Is there a reason for not prefixing all susy-lib related variables with e.g. 'susy-' to avoid conflicts?

**Comment by krzkrzkrz** [comment]
$base-line-height is also defined by default in bourbon bitters. Maybe prefixing variables is the way to go to avoid conflicts?
