### ISSUE TITLE
SVG instead of Gradients for Grid images 

### ISSUE THREAD

**Issue by g12n** [oddbird/susy#436]
Grid images are not exact due to the trouble with sub-pixel rounding on background images. 
I tested a way to generate a background-svg as data-attribute. The results are quite promising:

Check out this Pen: 
http://codepen.io/mi1980ge/pen/OPvPYb?editors=110

![svg-grid](https://cloud.githubusercontent.com/assets/57556/6232139/64a0dff4-b6ca-11e4-9a5d-fdc4e9ecfacd.png)

I would like to follow this track to see, if it leads to a better way to preview the grid. I am happy for any feedback and help!

**Comment by tsi** [comment]
That's genius!

**Comment by ericam** [comment]
Very cool! I'd love to see this worked into the core.

**Comment by g12n** [comment]
Thank you! I'll give it a try. What do you think? 

Would you prefer to add this as an additional option? Or rather as a replacement for the existing background functions?

**Comment by ericam** [comment]
I'd prefer letting it be a replacement if we can. Are there differences in browser support, or any other trade-offs we should be aware of?

**Comment by tsi** [comment]
SVG is well supported. I say replace it.

**Comment by g12n** [comment]
I will have to check that. Though I am sure that browsers that support CSS background gradients and scale should support this technique as well. But I wouldn't be totally shocked to stumble over one or two surprises on the way. 

Letting it be a replacement will make the implementation  much simpler to handle. :) you spared me some sleepless nights. 

I gonna run a few tests to make this work smooth. The math in the current pen is really ugly. I hope I can come up with a smarter solution.

**Comment by scottdavis** [comment]
Replace it! It should be assumed that if you are developing with susy you have access to all modern browsers.

**Comment by zellwk** [comment]
I'll say let this be the main format, and allow a background-image as an replacement :)

**Comment by g12n** [comment]
OK. So much about surprises. 
Do you guys know a method to fully url or base64 encode a string in SASS?

I created a svg-background-function that created a working background for every grid i could through at it:
http://codepen.io/mi1980ge/pen/LEdxyL

But I had problems in FF and IE. 
I checked the comments on this article by Chris Coyier:

http://css-tricks.com/probably-dont-base64-svg/

> Firefox 4+ supports < and >, but # must be url encoded
> <=IE11 needs to be fully encoded
> Chrome and Safari 5+ work just fine without encoding

**Comment by g12n** [comment]
OK, I wrote my own encoder:
http://codepen.io/mi1980ge/pen/MYVGGE

This should do the tick. I updated my pen accordingly: 
http://codepen.io/mi1980ge/pen/LEdxyL?editors=110

**Comment by ericam** [comment]
Cool. Make a pull request, and I'll take a closer look!

**Comment by g12n** [comment]
OK, Newbie Question:
I pushed the changes into the master branch of my susy-reposiritory, branched off this one:
https://github.com/g12n/susy/commit/cd0a0bbd5d3f503bb1e3763801f1526a70db4dd3

Is this correct, or should I make a pull request from a new branch. 
Considering that all tests have to be rewritten I guess there is a lot to do, to prepare this one for release.

**Comment by ericam** [comment]
I created an `svg-debug` branch off master here - so make that the target of your pull request, and the origin shouldn't matter (I think).

**Comment by g12n** [comment]
I added created the pull request: https://github.com/ericam/susy/pull/440
I am still not sure how to write those tests.

**Comment by jakob-e** [comment]
It seems like hide, show-baseline and show-columns are not working. Here is a simplified version with a little added to the if statements and without html-encode dependency.

````SCSS
@mixin background-grid($grid: $susy) {
    $columns: susy-count(susy-get(columns, $grid));
    $image: susy-get(debug image, $grid);
    $color: susy-get(debug color, $grid)+ unquote("");
    $color: if(str-index($color,'#'), '%23'+str-slice($color,2),$color);
    $height: 100%;
    $svg: "data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='#{$color}' %3E";
    @if $image != show-baseline and $image != hide {
        @for $i from 1 through $columns { 
            $x: isolate($i of $grid); 
            $span: span(1 at $i of $grid);
            $svg : $svg +  "%3Crect x='#{$x}' width='#{$span}' height='100%'/%3E";
        }
    }
     @if variable-exists(base-line-height) and $image != show-columns and $image != hide {
        $height: $base-line-height;
        $svg: $svg +"%3Cline x1='0' x2='100%' stroke='%23000' stroke-width='1'/%3E"
    }
    $svg: $svg +  "%3C/svg%3E";
    background-image: url($svg);
    background-size: 100% $height;
    background-position: 0 0;
    background-repeat:repeat-y;    
}

**Comment by mirisuzanne** [comment]
This has been implemented as a plugin for Susy 3: https://github.com/oddbird/susy/tree/threeish/sass/plugins/svg-grid
