### ISSUE TITLE
slideshare embed responsive with susy

### ISSUE THREAD

**Issue by webmasterpf** [oddbird/susy#533]
Hi,

I need to make responsive a slideshare embed into a div.Actually i use the same as the images (  max-width: 100%;) but form iframes.
No way to get it work.
Have you got a solution to this ? for youtube it work simple.

thanks

**Comment by HugoGiraudel** [comment]
Without a code sample or any info about your setup, it's gonna be hard for us to help.

**Comment by webmasterpf** [comment]
this is the embed code of the slideshare:
`<iframe allowfullscreen="" frameborder="0" id="slideshare-embed" marginheight="0" marginwidth="0" mozallowfullscreen="" scrolling="no" src="http://fr.slideshare.net/Lycee_Celony/slideshelf" style="border:none;" webkitallowfullscreen=""></iframe>`

then the compiled css code:
`#colonne-2.page-lycee iframe#slideshare-embed, #colonne-2.page-lycee iframe {
  max-width: 100%;
}`

the container scss:
`  @include breakpoint ($desktop){
          @include span(6 of $desktopcol no-gutters);
        
        }`

**Comment by mirisuzanne** [comment]
Yeah, the problem is with slideshare. They're content doesn't resize to fit the frame you design. You can't fix that with Susy.

**Comment by webmasterpf** [comment]
thanks for explanation
