### ISSUE TITLE
Overriding flow in with-context - working?

### ISSUE THREAD

**Issue by dbatiste** [oddbird/susy#539]
I'd like to be able to apply a different layout when content is marked up with the [dir='rtl'] attribute, for example on the body.  I am trying to use the `with-layout` mixin to do this.

```
<html>
   <body dir="rtl">
      ...
   </body>
</html>
```

```
.some-selector {

   @include span(5);

   [dir='rtl'] & {
      @include with-layout(rtl) {
         @include span(5);
      }
   }

}
```

However, the CSS output for both the `.some-selector` and `[dir='rtl'] .some-selector` is identical.  Should this be working?  The modified flow attribute (rtl) does not seem to be respected.  That is, the floats in both cases are left.

**Comment by ericam** [comment]
It's working for me [on Sassmeister](http://sassmeister.com/gist/ff3aa4e68d267c93cb74). But you are duplicating code you don't need to duplicate. All you really need is the `float` property override — why use `span` and get all the duplicate widths?

**Comment by ericam** [comment]
oh, I guess you might need the gutters flipped as well...

**Comment by dbatiste** [comment]
Thanks!  I must have something else in my code that is causing this.  I'll see if I can reproduce my issue on Sassmeister.

Yeah.  I'll need to flip the margin, but the width will be duplicated.  It'd be nice to not have the duplication.  I've managed to get it working if I add the flow attribute directly to the span:

```
.some-selector {

   @include span(5);

   [dir='rtl'] & {
      @include span(5 rtl);
   }

}
```

**Comment by dbatiste** [comment]
I've tracked down the source of my issue.  I've been able to reproduce the issue on Sassmeister by wrapping the `@import` statement in a selector.  Moving it out resolves the issue in my project.

```
.app {

  // moving this outside of .app fixes  
  @import 'susy';

  ...
}
```
