### ISSUE TITLE
Safari iOS 8 problems

### ISSUE THREAD

**Issue by jimzarkadas** [oddbird/susy#540]
I am using the gallery mixin but for some reason it doesn't work on my iPad which has iOS8 installed. It took me some days of debugging to find the cause and the result is that this happens because nth-child selector doesn't work on ios8 (http://stackoverflow.com/questions/27127879/nth-child-not-working-on-iossafari-8).

It's not a susy bug but I think you should add some notice somewhere or a JS temp fix.

Thanks a lot
- Jim

**Comment by kmuncie** [comment]
Yep, this was also a long and frustrating thing to debug for me. Now all of my gallery() are set to nth-of-type

**Comment by mirisuzanne** [comment]
Added to the docs in ddf6736

**Comment by mirisuzanne** [comment]
Thanks for reporting this!

**Comment by jimzarkadas** [comment]
@mirisuzanne awesome thanks :-)
