### ISSUE TITLE
Firefox and IE seem to zoom content

### ISSUE THREAD

**Issue by webmasterpf** [oddbird/susy#544]
Hi,

I need explaination about Firefox and IE different behaviour than chrome.This is examples : http://www.lycee-celony.com  or http://www.provence-formation.fr where content seem to be zoomed instead of chrome don't.
How can I fix this ? Which parameter rule this ?

thanks

**Comment by webmasterpf** [comment]
after testing, on my ubuntu firefox content is not zoomed..anyone know witch parameter rule this ?

**Comment by mirisuzanne** [comment]
I'm not sure what you are seeing, and I can't re-create it on either of your sites, but it doesn't sound like a Susy issue. You may want to provide screenshots or something. I assume you've already checked your browser zoom settings?

**Comment by webmasterpf** [comment]
yes I checked my browser zoom setting.And I note that happen on other websites I visit.So I think it's a browser issue or setting...
