### ISSUE TITLE
Question: How to use Susy without Ruby and Compass?

### ISSUE THREAD

**Issue by hellobrian** [oddbird/susy#550]
Hello,
I'm working on a Sass project for work.
We're using [gulp-sass](https://github.com/dlmanning/gulp-sass) to compile `scss` code and I was trying to start using Susyone for grids. 
I followed the bower install instructions [here](http://susydocs.oddbird.net/en/latest/install/#bower) and when compiling my `gulp-sass` task logged this error:

```bash
Error in plugin 'sass'
Message:
    bower_components/susy/sass/susy/language/susyone/_functions.scss
Error: File to import not found or unreadable: compass/typography/vertical_rhythm
       Parent style sheet: /Users/brianhan/ibm/WORK/bluemix-components/bower_components/susy/sass/susy/language/susyone/_functions.scss
        on line 5 of bower_components/susy/sass/susy/language/susyone/_functions.scss
>> @import "compass/typography/vertical_rhythm";
   ^
```

From this, the only clue I could gather was that compass is needed to use Susyone from the line: `Error: File to import not found or unreadable: compass/typography/vertical_rhythm`. 

I'm wondering if it's possible to use Susyone without Ruby and Compass?

cc: @una

**Comment by mirisuzanne** [comment]
SusyOne requires Compass, because Susy One required Compass. We kept it around, but we never updated it. I'd be happy to accept a patch for removing the Compass requirement, but I recommend using a more modern Susy.

**Comment by hellobrian** [comment]
Thanks @mirisuzanne it literally just hit me that I should've been importing susy instead of susyone.
