### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by vinkla** [oddbird/susy#552]
All of a sudden I'm getting `Segmentation fault: 11` when importing Susy into my project. I haven't changed anything in my build scripts or any version constraints.

```sass
@import 'susy/sass/susy';
```

I'm using `gulp-sass` to compile my SASS. Is anyone else getting this error?

**Comment by mirisuzanne** [comment]
We haven't gotten reports of this tied to Susy, but there are a lot of related issues on the gulp-sass and node-sass issue trackers. I'd look there.

You must have changed something, if you think this is Susy related. Did you just do a Susy update?

**Comment by brianjhanson** [comment]
I'm experiencing a similar issue. My project was compiling fine until I added Susy and now it's throwing a segmentation fault. It seems to be a Susy issue because when I comment out the import it compiles fine again.

**Comment by brianjhanson** [comment]
I narrowed mine down to an issue when gutters are set to 0 and you use the `container` mixin. Opened #553 for it.

**Comment by vinkla** [comment]
I've basically cloned a year old project which worked fine at the time but now it returns seg fault.

@brianjhanson yeah, sounds similar to what I'm experiencing. I'll try following your fix and see if it helps.

**Comment by vinkla** [comment]
I tried changing `@include container;` to `@include container(12);` and it started working again. Is this expected behaviour? Why did it work before?

**Comment by aguynamedirvin** [comment]
I'm using the latest Susy with Grunt-Sass to compile and I'm also having this problem. I did what @vinkla suggested and it seems to work but without it I get the "Segmentation fault: 11" error. Any fix?

**Comment by brianjhanson** [comment]
@aguynamedirvin not 100% sure but double check that your `$susy` map is getting loaded before the `@include container()` call. 

Easy way would be to put `@debug $susy` right before the `@include container()` and checking your console to see what value gets reported.

**Comment by luglio7** [comment]
Same problem.

**Comment by mirisuzanne** [comment]
Should be fixed by 38db5da. Must have been a change in libsass, because we haven't touched that code since July, and it worked fine in Ruby. Someone may want to report it over there.
