### ISSUE TITLE
Segmentation Fault in container() mixin.

### ISSUE THREAD

**Issue by brianjhanson** [oddbird/susy#553]
When you configure the global settings to have `gutters: 0` it the `container()` mixin causes a segmentation fault. 

Config that caused it for me
```
$susy: (
  output: isolate,
  container: auto,
  columns: 24,
  gutters: 0.25,
  global-box-sizing: border-box,
  debug: (
    image: show,
    color: rgba(#66f, .25),
    output: overlay,
    toggle: top right,
  ),
  use-custom: (
    background-image: true,
    background-options: false,
    box-sizing: true,
    clearfix: false,
    rem: true,
  )
);
```

### Versions
Susy — 2.2.9
Node Sass — 3.4.2
Gulp Sass — 2.1.0

**Comment by brianjhanson** [comment]
I spoke too soon, this is still happening anytime I use the container mixin.

**Comment by brianjhanson** [comment]
Also happens with the default config unfortunately.

**Comment by brianjhanson** [comment]
I'm able to get it to compile as long as I pass an argument into the mixing. So `container(24)` works, but `container` segfaults.

**Comment by brianjhanson** [comment]
Welp, closing this because as it turns out I'm just an idiot and forgot to actually import my susy configuration. As you were.

**Comment by vinkla** [comment]
This solution made it work for me as well #552 but I know `@include container;` has worked in the past.

**Comment by brianjhanson** [comment]
@vinkla for me it was because I hadn't defined the `$susy` variable anywhere in my project which caused it to blow up on a segfault.

**Comment by vinkla** [comment]
I still think it has to do with the container. In my case I'd the $susy variable defined.

**Comment by brianjhanson** [comment]
But if `container()` segfaults and `container(12)` works, it seems like it's not getting the default (or any) layout variable. Maybe try moving your `$susy` variable into the same file as your `container` call just to be sure?

**Comment by vinkla** [comment]
Yeah, maybe. We have it in many places. I had to do a careful find a replace in order to fix it.

**Comment by brianjhanson** [comment]
I'd recommend producing a reduced test case before doing that. Just have it compile one file with one `container` call. Make sure that's really the issue.

**Comment by vinkla** [comment]
Well, I know this is the issue. I added the 12 to the included containers which made it work again. This has worked before since I worked on the project a while back without any issues.

**Comment by mirisuzanne** [comment]
@vinkla I'd like to look into this, but I'll need steps that consistently reproduce the problem. Can you narrow it down to a code sample that consistently faults?

**Comment by vinkla** [comment]
I've just tested this and it seems it is the same error as @brianjhanson describes. When the Susy config is injected after i use the mixin is when it fails.
