### ISSUE TITLE
Wrong container width when using rem in IEs

### ISSUE THREAD

**Issue by hoffi** [oddbird/susy#554]
The width of my container is `950px` and the Base Font-Size is `16px`, this gives a rem-Value of `59,375`. 

But IE seems to only accept values with two decimal places, as it always uses `59,37rem`. The container is now `0,08px` to small in IE and so the contents do not fit into the container anymore and start wrapping.

As a workaround is there a way to just disable the use of `rem` for the container?

**Comment by mirisuzanne** [comment]
Susy doesn't convert your container value to rems. Can you show me a sample of your code? What's your `$susy` config look like, and how are you calling `container()`?

**Comment by hoffi** [comment]
Hi, im using susyone and im just calling it this way: `@include container;`

My settings:
```scss
$total-columns: 24;
$column-widht: 30px;
$gutter-width: 10px;
$container-style: static;
$grid-padding: 0;
```

If i look at [this mixin](https://github.com/oddbird/susy/blob/master/sass/susy/language/susyone/_grid.scss#L23) it does set rem values.

**Comment by mirisuzanne** [comment]
Huh, I think that's a bug in Compass. That function is only meant to convert `rem` to `px` for fallback, not the other way around. Strange that we haven't seen it until now. It's also a bug with big repercussions if we fix it: we'd have to deprecate and break backwards-compatibility. With Compass end-of-lifed, that's not very likely. We *could* make the change here, but I don't really want to maintain SusyOne indefinitely either. This sounds like your starting a new project, is there a reason you're using an old version of Susy?

**Comment by hoffi** [comment]
It's an older project and we have updated susy from an older version because of a rails upgrade. 

Would it be possible to introduce a setting which would turn the rem off?

**Comment by mirisuzanne** [comment]
Sure! Want to submit a PR?

**Comment by hoffi** [comment]
When is a new version containing this fix planned?

**Comment by mirisuzanne** [comment]
Done!

**Comment by mirisuzanne** [comment]
`2.2.10`

**Comment by hoffi** [comment]
Thanks!
