### ISSUE TITLE
Documentation addition/improvement for asymmetrical nesting?

### ISSUE THREAD

**Issue by marcvangend** [oddbird/susy#555]
When reading the docs about the nested function/mixin in an asymmetrical grid at http://susydocs.oddbird.net/en/latest/toolkit/#nested-context, I found the code example a bit confusing, and it seemed more complicated than it should be.

Currently the docs show this example:

    $grid: (1 2 3 2 1);
    
    .outer {
      @include span(3 of $grid at 2);

      $context: nested(3 of $grid at 2);
      .inner { @include span(2 of $context at 1); }
    }

If I am not mistaken, that code would be equivalent to:

    $grid: (1 2 3 2 1);

    .outer {
      $context: 3 of $grid at 2;
      @include span($context);

      @include nested($context) {
        .inner { @include span(2 at 1); }
      }
    }

The second syntax seems simpler and more readable (for me at least). More importantly, it offers the advantage that you only need to change one line of code (the $context variable) in case you need to move things around, for instance when `.outer` should start at the 3rd column instead of the 2nd.

Can you confirm that the two code examples are equivalent? Or is there a case when the first example works better than the second?

If you like, you're more than welcome to add my code example to the documentation.

**Comment by mirisuzanne** [comment]
Yep, updated in d25e81f — Thanks!
