### ISSUE TITLE
LoadError on line ["54"] of /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb: cannot load such file -- susy Run with --trace to see the full backtrace

### ISSUE THREAD

**Issue by themefisher** [oddbird/susy#558]
When I require susy in my config.rb file this issue is appears . 
My config file settings is here 
require 'susy'

http_path = "/"
sass_dir = "scss"
css_dir = "css"
images_dir = "img"
fonts_dir = "fonts"
javascripts_dir = "js"
line_comments = false
preferred_syntax = :scss
output_style = :expanded
relative_assets = true

My operating system is mac osx and I have all the updated files and using elcapitan . 
Thanks

**Comment by artemgurzhii** [comment]
Hi, did you find the answer? i have the same issue, and i hope you can help me
