### ISSUE TITLE
flow-direction auto

### ISSUE THREAD

**Issue by heyyoyo** [oddbird/susy#560]
It will be great to have another value **'auto'** for the variable flow-direction.

If it's in **auto** mode the span mixin will add automatically in css, the extra style [dir=rtl] with flow-direction: right.

I'm using the one css file approach for LTR and RTL, and it's quite consuming to add the mixin bi{} around all span mixin as proposed here by eric suzanne:
http://stackoverflow.com/questions/18337816/susy-responsive-grids-for-compass-text-direction/18341273#18341273

Or maybe there is an easy way that I'm missing.

**Comment by mirisuzanne** [comment]
What's the advantage of doing this inline with a single file? My instinct would be to go with two files, so you don't need to increase output and specificity every time you mention right or left. Especially since it's not likely that Susy would handle all instances of that - so you'll have to write your own mixin for all the non-susy cases.

I remember @chriseppstein talking about a post-css script that simply creates a second file with all instances of right/left flipped. The more common Susy approach is a second file with different Susy settings, but again that only solves the Susy side of the problem.

**Comment by heyyoyo** [comment]
Thanks for your answer, use only one sass file, is just faster development and really easier to maintain.
Maybe a question of habits, but I prefer to see the code of RTL and LTR in one same location, instead of switching between files.
Using 2 css files, it also means adding logic in the backend for serving the right version.

In multi-language website, it should be perfectly symmetrical, because it's the same content just translated.
I totally understand that it adds unnecessary overhead of css, but as soon this css file is loaded, it should be cached, and used in LTR or RTL version of the page.

Before using susy I was using the singularity library which was proposing this option.

But maybe I should look into this Flip script. Was it working on the SASS file or the CSS version ?

**Comment by mirisuzanne** [comment]
Oh, I agree that you don't want to maintain two different files - but the easiest solution is to *output* two different files. If you define your layouts in partials, you can import those partials into two different files for compilation - one with ltr settings, and the other with rtl settings. You only maintain the layout in one place, but you compile it two different ways. You might even be able to do that within a single file? I'd try something like this in your partials:

```scss
[dir='#{susy-get(flow)}'] {
  // all your layouts
  // using Susy's from() and to() functions anywhere you need "right" or "left"
}
```

and then something like this, to compile each partial twice in your final output:

```scss
$susy: (flow: ltr);
@import 'layout';

$susy: (flow: rtl);
@import 'layout';
```

**Comment by mirisuzanne** [comment]
`from()` and `to()` are not currently documented, which is an oversight. They just check the value of the `flow` setting, and return either `right` or `left` based on that. If the flow is `rtl` then `from() == 'right'` and so on.

**Comment by heyyoyo** [comment]
Thanks for your detailed explanations.
I'm now using your 2 css files approach generated from same partials but with different flow variable defined into 2 different SASS file : styles-rtl.scss & styles.scss.

Because syles-rtl.css will be loaded only in RTL context, dir='ltr|rtl' inside Sass files is not needed anymore.

my styles-rtl.scss:
```
@import 'mixins';
@import 'variables';

$susy: (flow: rtl);
@import 'grid';

@import 'html';
@import 'page/regions';
@import 'components/social/social';
```

and my _grid.scss:
```
@import 'susy';
$susy: (
  columns: 12,
  flow: #{susy-get(flow)}
);
...
```

Just for information in Drupal 8 which just came out, the approach which contains only one css file for LTR and RTL has been retained.
https://www.drupal.org/node/2032405

PS: too bad that we can't pass this flow variable directly from the compiler like libsass or compass, like this we don't need to make 2 main sass files.

**Comment by mirisuzanne** [comment]
Sounds good. You shouldn't need interpolation (`#{}`) for adding a `susy-get()` function to your settings map.

**Comment by heyyoyo** [comment]
Right I didn't pay attention to that.
Now I will have to modify my drupal to output ltr or rtl css styles according to the language.

Thanks for your help.

**Comment by rogerrogers** [comment]
I'm using something like this approach. It works fairly well really. However, by wrapping the entire sass styles block like:  

```
[dir='#{susy-get(flow)}'] {
  // all your layouts
  // using Susy's from() and to() functions anywhere you need "right" or "left"
}
```

Means that using & can get tricky when you are prepending, e.g. 

```
.wrapper {
   .style & { ... }
}
```

Because this will result in .`style [dir='ltr'] .wrapper`, when the desired result should be `[dir='ltr'] .style .wrapper`.

I've done this:

```
@mixin bi-root ($selector) {
	@at-root #{selector-replace(&, 'html[dir="' + $dir + '"]', 'html[dir="' + $dir + '"] ' + $selector)} {
		@content;
	}
}

```
... and then ...

```
.wrapper {
  @include bi-root('.style') {
     ...
  }
}
```

This helps with this problem. Though, I'm curious to know if there is a more elegant way to achieve this?

**Comment by mirisuzanne** [comment]
I don't see a better way to do it with selector manipulation in Sass. I'd probably try adding the `[dir]` selector outside of Sass, after compilation — since it's simple, and not something you ever want to manipulate. You could probably do that with a tool like postCSS.
