### ISSUE TITLE
Webpack integration issue

### ISSUE THREAD

**Issue by Kurniawandering** [oddbird/susy#561]
When I try to import susy from my manifest.scss

```
@import '~susy/sass/susy';

```
I get the following error:

```

Module build failed: CssSyntaxError

```

It is as if the file is not compiled by webpacks sass loader first. However, my other scss files are getting compiled corretly. Only this one from the node_modules is giving me error.

My webpack.config looks like this

``` javascript

    module: {
        loaders: [
            {
                test: /\.scss$/,          
                loader: ExtractTextPlugin.extract('style', 'css', 'sass')                
            }
        ]
    }

```

Anyone have an idea about this?

**Comment by mirisuzanne** [comment]
@jgerigmeyer any ideas here?

**Comment by gyfchong** [comment]
I also get an error when trying to use webpack/@import:
```Module build failed: 
    @if valid-column-math($_math, $_column-width) {
       ^
      Function valid-column-math did not return a value

Error: 
    @if valid-column-math($_math, $_column-width) {
       ^
      Function valid-column-math did not return a value
```

**Comment by jgerigmeyer** [comment]
@Kurniawandering I'm able to import ``susy`` without trouble, and I'm guessing it's related to your use of the ``ExtractTextPlugin``. I think the syntax should be ``ExtractTextPlugin.extract('style', 'css!sass')`` (see https://github.com/webpack/extract-text-webpack-plugin#api).

**Comment by mirisuzanne** [comment]
@gyfchong your issue is not related to webpack. Can you create a new issue for it?

**Comment by Kurniawandering** [comment]
@jgerigmeyer yes, I think you are right. Thanks for your help!

As far as I concern, we can close this issue
