### ISSUE TITLE
Module build fail

### ISSUE THREAD

**Issue by gyfchong** [oddbird/susy#562]
Hey guys,

I've installed the NPM version of Susy, and in my SCSS file I have:
```
@import "~susy/sass/susy";
```

But I'm getting this SASS error:
```
Module build failed: 
    @if valid-column-math($_math, $_column-width) {
       ^
      Function valid-column-math did not return a value

Error: 
    @if valid-column-math($_math, $_column-width) {
       ^
      Function valid-column-math did not return a value
```

Any help would be great!

**Comment by mirisuzanne** [comment]
That looks like a bug in your code, revealing a bug in ours. :)

This should throw an error, but is only throwing a warning:
https://github.com/oddbird/susy/blob/master/sass/susy/language/susy/_validation.scss#L12

Static math requires a valid `column-width` setting. Seems you have asked for static math, without providing the column-width to base it on.

**Comment by gyfchong** [comment]
Ah! I didn't set it in the Sass Map, thanks @mirisuzanne!
