### ISSUE TITLE
Problem with container auto

### ISSUE THREAD

**Issue by StfBauer** [oddbird/susy#563]
Actually it is no big deal but when I switch inside $susy the property container to 'auto' I get the following error. Any idea ?

bower_components/susy/sass/susy/su/_grid.scss
Error: invalid operands for multiplication
        on line 53 of bower_components/susy/sass/susy/su/_grid.scss
>>   @return $column-sum + $gutter-sum;
   ----------^

**Comment by mirisuzanne** [comment]
I would have to see you're other settings. Can you paste the full `$susy` map?

**Comment by StfBauer** [comment]
Surry sorry my bad. Here you go. Actually this happens when I set the container property to auto. If I set this to 100% it works strangely.

```$susy: (
  flow: ltr, // ltr | rtl
  output: float, // float | isolate
  math: fluid, // fluid | static (requires column-width)
  column-width: true, // false | value
  container: auto, // length or % | auto
  container-position: center, // left | center | right | <length> [*2] (grid padding)
  last-flow: to,
  columns: 12,
  gutters: 1/4,
  gutter-position: split, // before | after | split | inside | inside-static (requires column-width)
  global-box-sizing: border-box, // content-box | border-box (affects inside/inside-static)
  debug: (
    image: hide,
    color: rgba(#66f, .25),
    output: background, // background | overlay
    toggle: top right,
  ),
  use-custom: (
    background-image: true, // look for background-image mixin
    background-options: false, // look for background-size, -origin and -clip and other compass/bourbon mixins
    box-sizing: true, // look for custom bix sizing mixin
    clearfix: false, // true = look for internal clearfix before using micro clearfix
    rem: false, // look for rem mixin
  )
);```

**Comment by mirisuzanne** [comment]
`column-width: true` is causing your problem. `true` is not an option for `column-width`. It should either be `false` or a length value representing the width of a column. Your `auto` container will be calculated based on that width, and the number of columns in your grid. If you set it to `false`, your container will default to `100%`.

**Comment by StfBauer** [comment]
:+1: Thank you. Now everything is clear.
