### ISSUE TITLE
Content wider than grid?

### ISSUE THREAD

**Issue by track0x1** [oddbird/susy#564]
I am trying to create a grid with an element inside that is `span(full)`, but what I'm noticing is that the element is actually larger than full as it's bleeding into the gutter.

Please have a look here at the `some-content` class:
http://codepen.io/anon/pen/GoQmBd

Notice the far right side:
![screen shot 2016-01-23 at 12 32 09 pm](https://cloud.githubusercontent.com/assets/5631509/12531621/6121200a-c1cd-11e5-88c3-60f1453bbd2e.png)

**Comment by mirisuzanne** [comment]
The fact that it bleeds past the grid background-image does not mean it is actually bleeding into the gutters. Background image sizes are not precise on most browsers. There's a warning about that in the docs. Elements are laid out more accurately than backgrounds. The background image should only be used as a rough guide, not for checking px-perfect alignment.
