### ISSUE TITLE
How use susy-breakpoint() ? 

### ISSUE THREAD

**Issue by semiromid** [oddbird/susy#565]
I not find good example how use  susy-breakpoint() . In documntaticon example not is good. Help please me. How use susy-breakpoint() or breakpoint for susy?

**Comment by mirisuzanne** [comment]
Can you say more about what doesn't make sense to you? What have you tried? It's hard to explain in more detail when I'm not sure what was confusing about the first explanation.

**Comment by semiromid** [comment]
Very Hard  understand your  documentation. You need example : get started - step 1; step - 2; step - 3 ......   I not understand for what need - 'susy-breakpoint()'  if there is 'susy-media()'.

**Comment by nsams** [comment]
API documentation isn't necessarily a tutorial, you might read http://www.zell-weekeat.com/susy2-tutorial/ instead

**Comment by mirisuzanne** [comment]
`susy-breakpoint` will work *with or without* the [Breakpoint](https://github.com/at-import/breakpoint) plugin. If you are not using the breakpoint plugin, then `susy-media` is identical, and you can use either one. `susy-breakpoint` exists to handle the plugin integration.
