### ISSUE TITLE
Susy 2: Node-Sass warning in _padding.scss

### ISSUE THREAD

**Issue by sdempsey** [oddbird/susy#567]
Wanted to put this on your radar.  Updated a bunch of Grunt dependencies today on a project and now each time I save I get the following warning in the terminal:
`WARNING: Mixin susy-inspect takes 2 arguments but 3 were passed.
        on line 70 of /Users/SeanDempsey/sites/usd-wpengine/node_modules/susy/sass/susy/language/susy/_padding.scss
This will be an error in future versions of Sass.`

The offending line of `_padding.scss`:
```sass
@include susy-inspect(pad, $inspect...);
```

relevant packages:
```json
"grunt-sass": "^1.1.0",
 "susy": "^2.2.11"
```

Hoping I'm not reporting a bug I've created but just in case, here's my config.
```sass
$susy: (
    container: 1400px,
    columns: 12,
    gutters: 0.1683
);

@include layout($susy);
```

Not sure it matters but I'm using the pad mixin quite a bit. i've checked all of them and they seem to be correctly defined setting both prefix and suffix:
```sass
.container {
    @include pad(1.2rem);
}
```

Love,
Sean

**Comment by mirisuzanne** [comment]
This should be fixed by 6c10e82 and released in 2.2.12

**Comment by mirisuzanne** [comment]
It was a hold-over from #553

**Comment by sdempsey** [comment]
Awesome, thanks @mirisuzanne !
