### ISSUE TITLE
Call for help on compare.gs

### ISSUE THREAD

**Issue by corysimmons** [oddbird/susy#569]
So I removed my super biased/inaccurate comparison table from Lost's README. Sorry about that (a mix of ego and stupidity).

I still think there are a billion CSS grids out there and it would be nice if there was a tool to sift through them all so I made https://github.com/corysimmons/compare.gs

I don't want to fall into the same trap of trying to decide what makes a good or bad grid, or what features a grid has, by myself, so I'm officially asking anyone who is interested in grids to get involved.

Things I need unbiased help on:

- [creating a feature list and giving weight to features](https://github.com/corysimmons/compare.gs/issues/1)
- [determining which grids have which features](https://github.com/corysimmons/compare.gs/issues/4)

I know this isn't an issue with Susy, but I think this is a good spot to garner some attention from a knowledgeable audience of grid enthusiasts so please leave this Issue open for a little while

**Comment by mirisuzanne** [comment]
I'd be most into that idea if the tool has no opinions on weighting features. We should just collect as much information as possible, and let users filter by what is most important to them. Likely, I'd come to a site like that with the knowledge that I need something (for example):

- in Sass
- responsive
- using class names
- supporting flex-box

and I would want to filter down to the grids that have those features.

**Comment by corysimmons** [comment]
This is the point @peterramsing brought up. I'm interested in a project like that (and very well might make one in the next week or so since there seems to be interest in it), but I don't think compare.js is that kind of tool specifically. It's more of a "I want a general goto grid that I can reuse" rather than a "I have a specific set of requirements for a particular project".

In lieu of weighting features (which a sort method for that currently isn't even implemented), would you be interested in helping construct a list of features and grids that support those features? We could reuse that information/documentation on the "I need a particular tool that meets XYZ requirements" project.

**Comment by corysimmons** [comment]
Actually, I might be able to combine both our ideas. Like maybe if you search for `features: sass, responsive, flexbox` it can filter out columns and grids? Fair compromise?

**Comment by mirisuzanne** [comment]
Sure. Whatever direction you go, I'll be happy to give feedback and contribute ideas along the way. As for grid features, I think Susy (especially the next version) might pose an interesting challenge, in that it tries to live at a different level of abstraction than other systems do. Features comparisons between say, Susy and 960gs, are already pretty weird. I'm curious to see how you work with those more conceptual differences. This is why I never made a comparison chart, I'd way overthink it. :)

**Comment by zellwk** [comment]
Mind if I chipped in as well? ;)  
  

Stay awesome!

Zell

> On Jan 27 2016, at 8:16 am, Miriam Eric Suzanne
&lt;notifications@github.com&gt; wrote:  

>

> Sure. Whatever direction you go, I'll be happy to give feedback and
contribute ideas along the way. As for grid features, I think Susy (especially
the next version) might pose an interesting challenge, in that it tries to
live at a different level of abstraction than other systems do. Features
comparisons between say, Susy and 960gs, are already pretty weird. I'm curious
to see how you work with those more conceptual differences. This is why I
never made a comparison chart, I'd way overthink it. :)

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/oddbird
/susy/issues/569#issuecomment-175308156).![](https://github.com/notifications/
beacon/ADcMVTmUjqGFjP2sYbod1ASVMz5eKbM3ks5peAP2gaJpZM4HMxgg.gif)

**Comment by corysimmons** [comment]
@mirisuzanne If the next version of Susy is introducing some cool new concepts, you can [open an Issue ](https://github.com/corysimmons/compare.gs/issues/new) about what it is and the community can talk about it and whether or not it belongs on the chart. If it's related to grids, it probably does belong on the chart.

@zellwk Absolutely, that's why I posted the Issue rather than emailing people directly. As soon as I get this filter feature done, I'll work on adding some general features (that the community can get rid of if they want - I just want some real data on the chart).

Once I get some real data on the chart I think it's up to the community (people like you) to discuss what should go on the chart.
