### ISSUE TITLE
container gutter

### ISSUE THREAD

**Issue by tcurdt** [oddbird/susy#576]
Following up on [this SO thread](http://stackoverflow.com/questions/22383705/how-to-add-left-and-right-padding-to-containers-in-susy-2-0) I am opening this issue either to have the debug overlay fixed (which doesn't align correctly when there is a padding on the container element)

    $susy: (
      ...
      debug: (
        image: 'show',
        output: overlay,
        toggle: top left,
      )
      ...
    );

    #foo {
      @include container;
      padding-left: gutter(12);
      padding-right: gutter(12);
    }

or some other way to easily define a padding/margin for the container.

Or is there any other suggested way of doing this?

**Comment by mirisuzanne** [comment]
I'm open to a suggestion or a pull request if you have a good idea for how this should work — but I'm more focussed on v3 with any time I have. This feature won't live in the v3 core, but it could be added as a plugin.

**Comment by tcurdt** [comment]
Frankly speaking it feels more like a bug than a feature :)
The overlay is just wrong if the container has a padding. 

My work-around was to wrap things in another `div` (yuck!).

Right now I don't have a clear path forward on how to do this any better.
I was so hoping for a good advice from the authors - maybe then I could also work on a PR.

**Comment by mirisuzanne** [comment]
Ha, well certainly _that_ bit isn't a feature. :)

The overlay is just generated content on the container, which means you could add padding to it directly if you want. Which means you can add `padding: inherit;` — which means I'm an idiot and this has a very simple patch... :p 

This will solve your problem in the short term:

```
.container {
  @include container(show overlay);
  padding: 2rem;
  
  &:before {
    padding: inherit;
  }
}
```

We should be able to add that one padding line to the [overlay-grid](https://github.com/oddbird/susy/blob/master/sass/susy/language/susy/_background.scss#L61) mixin, and have it _just work_.

**Comment by tcurdt** [comment]
Nice one! That helped.

The debug grid is still very off though - is that another matter?
![screen shot 2016-03-05 at 13 56 44](https://cloud.githubusercontent.com/assets/13697/13547638/eaf4c1f0-e2da-11e5-93a0-e2acc4c6fa9a.png)
![screen shot 2016-03-05 at 13 58 02](https://cloud.githubusercontent.com/assets/13697/13547639/f13698f4-e2da-11e5-84ad-79e088287a2c.png)

**Comment by mirisuzanne** [comment]
That's a sub-pixel rounding browser bug, mentioned in our docs — and the reason I kinda hate the whole debug-grid feature to begin with. :) Nothing to be done about it, except to resize your browser until they line up (should happen every 12px on a 12-column grid).

**Comment by tcurdt** [comment]
Ah, so the grid is fine - just the debug grid is off?

I read this in the docs but didn't think this would accumulate. I would have though that `position = col * colwidth` (instead of colwidth+colwidth+colwidth+...) could position the columns correctly (except for subpixels) - so it could be max 1 pixel off.

On the other hand if it's not perfect either is probably not much better. Anyway!
Not related so I'll close this issue. Thanks for the help!

**Comment by mirisuzanne** [comment]
Yeah, I tried a number of different background-image approaches to eliminate compounding the error, but nothing worked. The options were to compound by screen-size, or by column-count. In the end, I went with the latter, since it's more consistent. :p
