### ISSUE TITLE
How to use inside-static for a kind of layout ?

### ISSUE THREAD

**Issue by webmasterpf** [oddbird/susy#578]
Hi,

I need to build a 5 columns equal width layout and I saw that `inside-static` could do the trick.
So I would to know how to change the context for this layout only , and so use `inside-static`.
If you have some examples... ;)

thanks

**Comment by mirisuzanne** [comment]
You can create a block with custom layout settings:

```scss
@include with-layout(inside-static) {
  // your code here...
}
```

Or pass the settings to each individual element:

```scss
.things {
  @include span(5 inside-static);
}
```

**Comment by webmasterpf** [comment]
I test the second way like this: 
```
body .conteneur{
    .layout_5col{
        @include span(5 inside-static);
    }
}
```
and applied like this:
```
  <div class="layout_5col">
/.. some content
        </div>
```
but this create a wide column...so what's about the '5' ? a column number ? the width of a single column ?

thanks

**Comment by webmasterpf** [comment]
other test :
```
@include with-layout(inside-static){
    body .conteneur{
        .layout_5col_is{
            @include breakpoint ($desktop){
                @include span($desktopcol/5 of $desktopcol);
            }
        }
    }
} 
```
works better, like I would...

**Comment by mirisuzanne** [comment]
Sorry I don't have much information about your context here, so it's hard to say. My second example wasn't great. It should be something more like this:

```scss
.things {
  @include span(1 of 5 inside-static);
}
```

Where `1` is the span, and `5` is the context you want. The key is to understand that you can change the context however you want. It doesn't matter what your global grid looks like, if you want to nest a different grid inside it, you can set any new context you want. Your second example is fine, but if you don't have other code inside your `with-layout` block, this is simpler:

```scss
body .conteneur {
  .layout_5col_is {
    @include breakpoint ($desktop) {
      @include span($desktopcol/5 of $desktopcol inside-static);
    }
  }
}
```

**Comment by webmasterpf** [comment]
thanks for explanation. :+1:
