### ISSUE TITLE
Not an issue but a question :)

### ISSUE THREAD

**Issue by FrederiqueGame** [oddbird/susy#581]
I really love Suzy and find it so amazing.

Which is the best way to write code lines 👍  to let breakpoints ? At each change or at the end of the complete set-up ? 

I explain my question :

### option A :

.site {blablabla}
.content
.widget...
.class {blablabala}

and here @include susy-breakpoint {mychanges}
at the end

**or**

### option B

.site {blablabla}
 @include suzy-breakpoint {mychanges}

.content
 @include suzy-breakpoint {mychanges}

.widget...
 @include suzy-breakpoint {mychanges}

.class {blablabala}
 @include suzy-breakpoint {mychanges}

Is that make sense or it's exactly equal ?

Thanks a lot !!

**Comment by mirisuzanne** [comment]
I prefer option B, simply for maintainability. If you are ever writing CSS that *overrides* other CSS, I think it is best for the original code and the override to be as close to each other as possible — so the connection remains clear.

**Comment by FrederiqueGame** [comment]
Thanks a lot :) it makes sense 👍  Have a wonderful day !
