### ISSUE TITLE
Stylus support

### ISSUE THREAD

**Issue by jeka1985** [oddbird/susy#582]
Hi all, Is there any plans to adapt Susy for [Stylus](http://stylus-lang.com/) preprocessor ?

**Comment by mirisuzanne** [comment]
Not on our end, but it's open-source, so you're welcome to! If you want to make it "official" somehow, we can talk more about how to do that. We also have v3 on the way, which is much simpler, and would be easier to port.

**Comment by jeka1985** [comment]
@mirisuzanne  thanks for quick response. Sounds great, will get back to this question as soon as v3 will be released, btw what is an approximate v3 release date ?

**Comment by mirisuzanne** [comment]
I don't have an approximate date. It's not far from done, but it's a matter of finding the time.
