### ISSUE TITLE
Error in webpack build with lightness

### ISSUE THREAD

**Issue by clexi** [oddbird/susy#587]
got this error:

`Module build failed:
    $gray-darker:           color(black lightness(+13.5%)); /* #222 */
                                       ^
          Argument `$color` of `lightness($color)` must be a color`

installed susy via npm and use webpack, sass-loader is enabled. 

`    test: /\.scss$/,
                loaders: [
                    'isomorphic-style-loader',
                    `css-loader?${DEBUG ? 'sourceMap&' : 'minimize&'}modules&localIdentName=` +
                    `${DEBUG ? '[name]_[local]_[hash:base64:3]' : '[hash:base64:4]'}`,
                    'postcss-loader?parser=postcss-scss',
                    'sass-loader?sourceMap'
                ],`

Started with the React Starter Kit https://github.com/kriasoft/react-starter-kit

**Comment by mirisuzanne** [comment]
Susy doesn't have any `color()` function, so this is not a Susy issue.

If you are trying to use oddbird/accoutrement-color, you have the syntax wrong. `$gray-darker: color(black (lighten, 13.5%));` might do what you want. If you have more questions about that, open a new issue on that project.
