### ISSUE TITLE
Postcss version

### ISSUE THREAD

**Issue by kyvour** [oddbird/susy#589]
First of all I want to say that susy is wonderful grid system which allow you feel free to build any layouts as you need. In the another side postcss (http://postcss.org/) is a tool with many possibilities and it can replace sass in many cases as for me. But postcss hasn't good plugin for grid building. And will be really good to have postcss support in susy.

**Comment by mirisuzanne** [comment]
Sass is designed specifically to support tools like Susy around a shared syntax and vibrant community. Postcss is designed to let individuals do anything they want, without a consistent syntax. I'm personally not interested in trying to write or support Susy in that ecosystem. But everything here is open-source, so if someone else wants to build it I'll answer any questions and point interested users in the right direction.

**Comment by kyvour** [comment]
Thanks for your answer.

What is susy 3 state now? As I understand 3rd version is absolutely different.
I want try to adapt susy for postcss, but probably will be better use 3rd version for this experiment

**Comment by mirisuzanne** [comment]
3 is much simpler, and should be about done if I get a chance to finish it up...

**Comment by kyvour** [comment]
Ok
Will try to use susy 3

**Comment by ivangretsky** [comment]
A bit off topic, but nice to hear that Susy 3 is on its way. Please do finish it, whatever it is. The "three" branch seems to be outdated though. Probably the code is elsewhere.

**Comment by mirisuzanne** [comment]
"threeish" has become the leading branch. I have plans to work on it again soon.
