### ISSUE TITLE
Composer Repo Packagist.org

### ISSUE THREAD

**Issue by djmwj** [oddbird/susy#592]
Is there a Repo for susy so that one can load via composer? Looking in Packagist.org does not list this package. Can one be added?

**Comment by mirisuzanne** [comment]
Packagist.org is for PHP packages. Our code is available to download right here, or on NPM as a node package, or on RubyGems.org as a ruby gem. If you are using Compass, you probably want the ruby gem.

**Comment by scottdavis** [comment]
@djmwj with composer you can just point it to the susy github and give it the git tag for the version

**Comment by mirisuzanne** [comment]
oh, I'm sorry, I didn't see the Compass->Composer edit. Thanks, @scottdavis.

**Comment by djmwj** [comment]
@scottdavis Thanks for the help. I have tried this and it fails with the following:

`
Reading composer.json of git@github.com:oddbird/susy.git (2.2.12)
Skipped tag 2.2.12, no composer file
`
I see that ther is a composer.json file, the only potential issue i see with that file from a composer perspective is that it does not use "oddbird/susy" as its name but rather just "susy". 

Are other correctly downloading this via composer?

**Comment by nsams** [comment]
@djmwj you need to define the package as the repo doesn't have a composer.json: http://stackoverflow.com/a/14485706/781662

Or, you use a composer plugin that allows installation of bower packages: https://github.com/fxpio/composer-asset-plugin or https://github.com/koala-framework/composer-extra-assets

**Comment by mirisuzanne** [comment]
I don't know anything about Composer, but I would consider a pull-request to add support if it just requires a simple json file like npm.

**Comment by mabar** [comment]
It is not good idea to allow sass project to be installed as php dependency. If you want handle it via composer so you can use [this](https://github.com/fxpio/composer-asset-plugin)
