### ISSUE TITLE
How do I Use Susy and compass .

### ISSUE THREAD

**Issue by devqx** [oddbird/susy#603]
Please can you the correct way to link both of these two together to use for projects, what i noticed was that when i install susy alone on my mac , i can compile with no error but using it with compass creates errors while compiling using compass. I get errors, or maybe am not getting the right steps,
please help direct. thanks

**Comment by mirisuzanne** [comment]
Hi @devqx. I'd have to see the errors in order to help.

You should also know that Compass is end-of-life, and no longer being developed or supported. I recommend moving off Compass if you can.

**Comment by devqx** [comment]
Since not been developed or supported again, maybe I will just stick to bourbon then. Is that okay too?                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Miriam SuzanneSent: Wednesday, October 5, 2016 5:26 PMTo: oddbird/susyReply To: oddbird/susyCc: devqx; MentionSubject: Re: [oddbird/susy] How do I Use Susy and compass . (#603)Hi @devqx. I'd have to see the errors in order to help.

You should also know that Compass is end-of-life, and no longer being developed or supported. I recommend moving off Compass if you can. 

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/oddbird/susy","title":"oddbird/susy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/oddbird/susy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mirisuzanne in #603: Hi @devqx. I'd have to see the errors in order to help.\r\n\r\nYou should also know that Compass is end-of-life, and no longer being developed or supported. I recommend moving off Compass if you can. "}],"action":{"name":"View Issue","url":"https://github.com/oddbird/susy/issues/603#issuecomment-251725821"}}}

**Comment by mirisuzanne** [comment]
Of course! Bourbon and Susy should work great together.

**Comment by devqx** [comment]
Ok, thanks for reaching out. My first post on git hub though!                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Miriam SuzanneSent: Wednesday, October 5, 2016 6:38 PMTo: oddbird/susyReply To: oddbird/susyCc: devqx; MentionSubject: Re: [oddbird/susy] How do I Use Susy and compass . (#603)Of course! Bourbon and Susy should work great together.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/oddbird/susy","title":"oddbird/susy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/oddbird/susy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mirisuzanne in #603: Of course! Bourbon and Susy should work great together."}],"action":{"name":"View Issue","url":"https://github.com/oddbird/susy/issues/603#issuecomment-251744812"}}}
