### ISSUE TITLE
Working with "with-layout" in Susy 3 alpha

### ISSUE THREAD

**Issue by mhlozek** [oddbird/susy#604]
I use something like that in my susy setup:

```
$bootstrap-layout: (
    columns: 12,
    gutter-position: split
);

@include with-layout($bootstrap-layout) {
.container {
        @include container();
        padding-left:  gutter();
        padding-right: gutter();
    }

    .row {
        @include susy-clearfix;
        margin: 0 gutter() * -1;
    }
...
}
```

I try to upgrade to Susy 3, but I get this error: Error: no mixin named with-layout.
Is there any way how to use (or simulate) with-layout mixin?

**Comment by mirisuzanne** [comment]
Susy 3 is fundamentally different from Susy 1 & 2, so you'll run into a lot of issues like this if you are updating an old project. Susy 3 doesn't have any mixins, so it also doesn't have settings related to output. In your code, that means `gutter-position`, `with-layout`, `container`, and `susy-clearfix` are all gone. 

I put together a gist showing how you can write and use your own `with-layout`-like mixin:

https://gist.github.com/mirisuzanne/9b5ca9df6642173e20058853031b8d88

You can do something similar to rebuild any other mixins you want.
