### ISSUE TITLE
Susy is ignoring 'gutters' and 'gutter-position' in my $susy map

### ISSUE THREAD

**Issue by IAMtheIAM** [oddbird/susy#605]
I have been using Susy2 for a year now, its awesome. Great work on it and I'm looking forward to the next version as well.

For some reason, in my project Susy is ignoring my properties "gutters" and "gutter-position" in my map.

```
$susy: (
   columns: 24,
   container: $hd-widescreen,
   global-box-sizing: border-box,
   gutters: 1/4, //<gutter-width>/<column-width> = // 20px gutters & 70px columns
   gutter-position: after,
   use-custom: (
      clearfix: false,
      background-image: true,
      breakpoint: true,
      box-sizing: false,
   ),
   debug: (
      image: $susyDebug,
      output: overlay, //background, overlay
      toggle: bottom right,
   ),
);
```

My SCSS

```
      @include nested(24) {

         .col_subscriber-search {
            @include span(3);
         }
         .col_problem-statement {
            @include span(6);

         }
         .col_support-info {
            @include span(4);

         }
         .col_solution {
            @include span(6);

         }
         .col_action-buttons {
            @include span(5 last);

            .input-field {
               max-width: 85%;
            }

            //.input-field {
            //   width: span(1 of 2);
            //   display: inline-block;
            //
            //   &:nth-child(2) {
            //      width: span(1 of 2 last);
            //      margin-left: gutter(3);
            //
            //   }
            //}

         }
      }
      // end nested(24)
```

The gutters are calculating to `margin-right: 0.84034%;`  for each of those selectors. If I change my susy map `gutters` to `1/4`, `1/2` or anything, or even change `gutter-position` to `before` - it does not change the calcluation and still uses `margin-right`. I never had this happen before.

What could cause that to happen?

**Comment by mirisuzanne** [comment]
I can't [reproduce this in Sassmeister](http://www.sassmeister.com/gist/f182a954c1203006a8325fdacb55db79). When I change the gutter setting, everything updates as expected. Are you sure everything is compiling without errors?

As a side note, your `nested(24)` mixin is not currently doing anything, since `24` is also your global columns setting.

**Comment by IAMtheIAM** [comment]
Thanks for the quick reply. I will dive deeper and see what is going on so I can provide more specific information. 

Also, good to know that the nested(24) isn't needed :-)

**Comment by mabar** [comment]
@IAMtheIAM 
Do you have this problem with only susy installed? If answer is no so it's probably collision, not susy problem.

**Comment by mirisuzanne** [comment]
Closing this for now, since I haven't heard any updates.
