### ISSUE TITLE
Default of `1` for `span()`

### ISSUE THREAD

**Issue by robsonsobral** [oddbird/susy#608]
Hi!

My logic: `gutter()` means "one gutter". So, shouldn't `span()` fallback to `span(1)` automatically?

Thank you!

---

I'm using treeish version.

**Comment by robsonsobral** [comment]
Of course, this opens the door for `gutter(2)`, which I don't think it's a bad idea.

**Comment by mirisuzanne** [comment]
I'm open to the idea of a default `span`, but `gutter(2)` already has a meaning — where `2` is the nesting context, not the number of gutters.

**Comment by robsonsobral** [comment]
> [...] `gutter(2)` already has a meaning — where 2 is the nesting context, not the number of gutters.

Oh, I'm sorry! I'm a susy newbie.

**Comment by mirisuzanne** [comment]
Not a problem! Thanks for the feedback!

**Comment by narration-sd** [comment]
But it seems a good idea, Robson – no reason there couldn’t be a second argument to work as you suppose, is there? 

Or am I too far out of date using Susy (still chugging along on sites) to remember how it’s supposed to work on gutters??

**Comment by mirisuzanne** [comment]
We can always add new arguments, but we should only do that with caution. Every argument adds complexity to understanding the Susy API. Handling this sort of simple multiplication is significantly _more readable_ without adding an argument:

```scss
.example {
  margin-left: gutter(12) * 2;
  margin-right: gutter(12, 2);
}
```

**Comment by narration-sd** [comment]
That’s a very good point, thanks – good to keep it factored separately, with the wider picture.

**Comment by mirisuzanne** [comment]
I played around with adding a default span, but I think it makes things less readable without saving much effort. Basically we'd be saving a single keystroke to create a default that I'm not sure is the most common usage — all while making the code less understandable at a glance. I don't think those tradeoffs are worth it.
