### ISSUE TITLE
grid image threeish style

### ISSUE THREAD

**Issue by robsonsobral** [oddbird/susy#609]
Hi!

Why not to have a debug image on v3?

I've been using susy in my first project and loving it, but a way to debug it is missing a lot.

``` sass
body {
    position: relative;

    &:before {
        background: transparent url(grid-image()) repeat-y left top;
        content: '';
        pointer-events: none;
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        z-index: z-layer('modal');

        @include media('>=76.875em') {
            background-position: 50% top;
        }
    }
```

I know you want to keep susy simple, so I had a look into other discussions here and tried to cover all bases while keeping it as simple as I can. I tried my best, but I'm no expert.

``` sass
$_svg-units: 'em', 'ex', 'px', 'pt', 'pc', 'cm', 'mm', 'in', '%';
$debug-color: #f00;

@function grid-image($grid: $susy) {
    // to use double single quotes inside the string save us from encode the double ones
    // scss-lint:disable StringQuotes
    $grid: susy-normalize($grid);

    $columns: map-get($grid, 'columns');
    $gutter: map-get($grid, 'gutters');

    @if index($_svg-units, unit($gutter)) == null {
        @error "SVG unsuported unit used for gutter: #{unit($gutter)}";
    }

    $color: $debug-color + unquote("");
    $color: if(str-index($color, '#'), '%23' + str-slice($color, 2), $color);

    $x: 0;

    $svg: "%3Crect x='#{$x}' width='#{$gutter}' height='100%' fill='#{$color}' opacity='0.5'/%3E";

    @each $column in $columns {
        @if index($_svg-units, unit($column)) == null {
            @error "SVG unsuported unit used for column: #{unit($column)}";
        }

        $x: $x + $gutter + $column;

        $svg: $svg + "%3Crect x='#{$x}' width='#{$gutter}' height='100%' fill='#{$color}' opacity='0.5'/%3E";
    }

    $x: $x + $gutter;

    $svg: "data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='#{$x}' height='1#{unit($gutter)}'%3E" + $svg + "%3C/svg%3E";

    @return $svg;
}
```

Thank you for your attention, patience and for susy.

**Comment by robsonsobral** [comment]
Oh, and I know you gonna point a lot of things that should be done differently, functions to call for, etc, etc...

**Comment by mirisuzanne** [comment]
I'm interested in this. Nice job setting it up as a function. I'll have to dig into it more this week. If we don't put it in the core, I'd certainly consider making it an official plugin. :)

**Comment by robsonsobral** [comment]
Thank you for your kind words, Miriam. There's probably a better way to get the full width of the grid and that I should have set `%` as unit for unitless grids, but everything is so... So well divided into tiny little functions that I got lost.

If I may... My opinion is that it should be part of the core. It's weird to have to install a plugin just to see what you're doing.

As susy3, this functions makes no assumptions on "how" you're working, You can use as `content` or as `background`, you can change the `background-size`, the `background-repeat`, or to use it inside of just one element, to have a grid for the first half of page and another to the rest... So, I guess the idea fits.

Thank you!

**Comment by narration-sd** [comment]
But plug-in seems fine; helpful for when we want those, and this way keeps
the dimensions of testing and understanding the core down, by is
modularity,  no?

**Comment by mirisuzanne** [comment]
There will always be a trade-off between what's in core and what's a plugin. The main criteria will be: how effective and flexible is this for *all* use-cases? I'll take a closer look this week, and let you know what I think.

**Comment by mirisuzanne** [comment]
@robsonsobral Sorry it took so long. I played around with this, and I think I've found a version that might be flexible enough to ship. See PR #617 — based on your work above. I made a few changes to the math, and broke it into smaller functions where I could. There are still a few issues, and a bit of cleanup:

- [ ] How do you make columns visible when there are no gutters?
- [ ] Need to test against various grid types, to make sure the `offset` feature works properly
- [ ] Test all functions
- [ ] Document all functions

**Comment by mirisuzanne** [comment]
So far the API looks like this: `susy-svg-grid($grid, $colors, $offset)`

- I think the automatic offset is pretty smart, but I don't quite trust it completely. We may find that override isn't needed.
- You can pass in a list of colors for `$colors` and it will generate a gradient, which helps when there aren't visible gutters. The default is a subtle gradient.

**Comment by robsonsobral** [comment]
I'm sorry, @mirisuzanne, but I can't look at this right now. I'm really busy.

Thank you for take the time to implement this. Thank you!

**Comment by mirisuzanne** [comment]
@robsonsobral No hurry! I'll start making visual integration tests for different grid types, and then we can use those to test how flexible the grid background is.

**Comment by mirisuzanne** [comment]
Are there any known use-cases where svg data would be used outside the `url()` function? If not, we should add that wrapper by default.

**Comment by robsonsobral** [comment]
I can't imagine any case, but... But... For me, it looks weird. Who knows what can appears tomorrow on css specification? I learned to try to avoid future issues caused by taking assumptions.

Anyway. Go ahead, @mirisuzanne . It's just my opinion. You're the boss, here!

**Comment by mirisuzanne** [comment]
Merged. I'll release another alpha. Still happy for retroactive review if you ever have time.
