### ISSUE TITLE
Breakpoint Plugin - changing library

### ISSUE THREAD

**Issue by gwgw** [oddbird/susy#613]
Hi, first, thank you for your susy library, and sorry for my poor english.
Would you considerate to change breakpoint plugin code to Zell Liew 
mappy breakpoint library ??
Its have this little calculation that:
"It will also minus off 1px from the max-width query to ensure that your breakpoints don't overlap each other."
And its cool, i'm using this right now, will this improve something, or its just imagination ?

**Comment by mabar** [comment]
Integration of breakpoint library is probably harder than handling it yourself. Only breakpoint library, which can handle all types of breakpoint is [nirazul/include-media-or](https://github.com/nirazul/include-media-or). Integration of these projects is not something, what anyone want to do.

**Comment by mirisuzanne** [comment]
@zellwk Do you want to weigh in on this, and what it would take, and if it's worth doing in 2.x still?

**Comment by zellwk** [comment]
I totally missed this O.O. 

But think there’s no need to integrate the breakpoint plugins :)
