### ISSUE TITLE
one pixel missing when using "fluid"

### ISSUE THREAD

**Issue by Shaker-Hamdi** [oddbird/susy#615]
Hi, I want to achieve a fluid layout, and wheneven I use math: fluid, the first column is alwayse missing one pixel for some reason.

Here's my settings ...

```
$susy: (
    flow: ltr,
    math: fluid,
    // math: static,
    columns: 12,
    column-width: 70px,
    gutters: 30px/70px,
    output: float,
    gutter-position: split,
    global-box-sizing: border-box
);
```

This is a 1200px grid which gives you a 1170px working area inside the container, that works just fine when using the mat: static, but when using math: fluid for some reason the first column is always 69px not 70px, which gives you a 1169px working area inside the container, here's an example ...

```
<div class="container">
    <div class="column"></div>
    <div class="column"></div>
    <div class="column"></div>
    <div class="column"></div>
    <div class="column"></div>
    <div class="column"></div>
    <div class="column"></div>
    <div class="column"></div>
    <div class="column"></div>
    <div class="column"></div>
    <div class="column"></div>
    <div class="column"></div>
</div>
```

```
div.container {
    @include container;
}
div.column {
    height: 150px;
    background: red;
    @include span(1);
}
```

How to achieve a perfect 1170px 12 columns with math: fluid?

**Comment by mirisuzanne** [comment]
This sounds like a sub-pixel rounding issue, which is somewhat unavoidable with fluid layouts. Here's an old article [detailing the problem](http://ejohn.org/blog/sub-pixel-problems-in-css/) browser-by-browser. In your example, Susy is only setting one value, a percentage applied that value to all the columns. The difference in how that percentage is applied to columns happens in the browser rendering. You'll likely get different results on different browsers.

We do have some tools for helping mitigate the worst layout-breaking sub-pixel issues.

- When you have a set of equal-width columns (like above), try the `gallery` mixin. It uses [float-isolation](https://www.palantir.net/blog/responsive-design-s-dirty-little-secret) to make sure the rounding errors don't compound. 
- [Isolate](http://susydocs.oddbird.net/en/latest/settings/#output) is also one of the `output` options in Susy - though it only works when all siblings are isolated, and it uses complex margins which can be inconveniant and bloated.

But generally it's worth remembering, by definition: a fluid layout is never directly related to pixel values, so a fluid design can never rely on pixel-exact rendering.
