### ISSUE TITLE
UNMET PEER DEPENDENCY sassdoc

### ISSUE THREAD

**Issue by robsonsobral** [oddbird/susy#634]
Hi, @mirisuzanne . I'm getting NPM warnings because of susy:

- `UNMET PEER DEPENDENCY sassdoc@^2.1.20`
- `npm WARN sassdoc-theme-herman@0.5.5 requires a peer of sassdoc@^2.1.20 but none was installed.`

Isn't any dependency missing?

Thank you!

**Comment by mirisuzanne** [comment]
I assume this is Susy 3? I'll take a look, thanks!

**Comment by mirisuzanne** [comment]
This has been resolved.
