### ISSUE TITLE
`5 x 120px` on new docs

### ISSUE THREAD

**Issue by robsonsobral** [oddbird/susy#642]
@mirisuzanne, good morning.

The new docs doesn't mention the deprecation of the old `x` syntax.

**Comment by mirisuzanne** [comment]
Does it mention the old syntax, or just not mention the deprecation? I searched the project for `5 x 120px`, and didn't find anything.

**Comment by robsonsobral** [comment]
It doesn't mention the (sad) deprecation.

**Comment by mirisuzanne** [comment]
This is mentioned now. Sorry for the sad deprecation!
