### ISSUE TITLE
No mixin named container - Npm Susy@3.0.0

### ISSUE THREAD

**Issue by frankn11** [oddbird/susy#645]
Can't compile my Sass with the new version of Susy since it doesn't know the mixin container. Tested with Gulp and Webpack, Node 8 and 6, Alpine and Debian Jessie. It always give the same error:

`Error: no mixin named container`

For this line:

`@include container;`

Tested and working under Npm Susy@2.2.12

**Comment by mirisuzanne** [comment]
3.0 has many breaking changes from the previous version. It's not a direct upgrade from 2.x. We removed all the mixins, including `container`. Check out [the docs](http://oddbird.net/susy/docs) for details, or read the [article introducing Susy3](http://oddbird.net/2017/06/28/susy3/) for more overview.

**Comment by bartekkorzeniowski** [comment]
Hi there I've got a similar error: no mixin named transition at Susy ver. 2.2.14 in Woocommerce's Storefront. Any ideas?

Error in plugin "sass"
Message:
    storefront/assets/css/woocommerce/woocommerce.scss
Error: no mixin named transition
        on line 2831 of storefront/assets/css/woocommerce/woocommerce.scss, in mixin `@content`
        from line 52 of node_modules/susy/sass/susy/language/susy/_breakpoint-plugin.scss, in mixin `susy-media`
        from line 1881 of storefront/assets/css/woocommerce/woocommerce.scss
>>                              @include transition( left 0.3s ease-out );

**Comment by mirisuzanne** [comment]
@bartekkorzeniowski Susy has never had a `transition` mixin, and I don't know anything about Woocommerce. The `susy-media` mixin referenced in the error message is simply a wrapper mixin, which would be mentioned any time the error occurs inside it's wrapper. Susy has nothing to do with the actual error here.

**Comment by hisuwh** [comment]
Is there a migration guide - your intro to susy3 makes no mention of the susy-media mixin.  How do I achieve the same thing with the new version?

**Comment by mirisuzanne** [comment]
@hisuwh we have not written a full migration guide – but we do have [an entire article about handling media queries](https://www.oddbird.net/2017/09/25/susy-use/), which should be helpful.
