### ISSUE TITLE
Unable to use SUSY v3 in includePaths

### ISSUE THREAD

**Issue by cedon** [oddbird/susy#647]
I am having the same problem as referenced in #433. I have the following code in my `gulpfile.js`:

    var susy = require('susy').includePaths;
    gulp.task('css', function() {
        return gulp.src(scss + '{style.scss,rtl.scss}')
        .pipe(sourcemaps.init())
        .pipe(sass({
            includePaths: susy,
            outputStyle: 'expanded',
            indentType: 'tab',
            indentWidth: 1
        }).on('error', sass.logError()))
        .pipe(postcss([
            autoprefixer('last 2 versions', '> 1%')
        ]))
        .pipe(sourcemaps.write(scss + 'maps'))
        .pipe(gulp.dest(root));
    }); // End CSS

When I execute this task, I get the following error:

    D:\WordPress\Themes\0 Gulp\node_modules\susy\sass\_susy.scss:4
    @import 'susy-prefix';
    ^
    SyntaxError: Invalid or unexpected token
        at Object.exports.runInThisContext (vm.js:76:16)
        at Module._compile (module.js:542:28)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (D:\WordPress\Themes\0 Gulp\gulpfile.js:19:36)
        at Module._compile (module.js:570:32)

**Comment by mirisuzanne** [comment]
@jgerigmeyer or @aaronagray – either of you know what might cause this?

**Comment by jgerigmeyer** [comment]
@cedon As shown in the README section on using Susy with Gulp (https://github.com/oddbird/susy#using-gulp), the `includePaths` option passed through to `sass` should point to the `node_modules/susy/sass` directory. Replace your `susy` variable (currently pointing to `require('susy').includePaths` with that, and it should work.

The error itself is actually coming from the `require('susy').includePaths` line. Because the `main` setting in Susy's `package.json` points to `sass/_susy.scss`, `require('susy')` is trying to import that Sass file, and node.js doesn't know what to do with it.

**Comment by cedon** [comment]
Thanks. I did get that to work. I had tried that method earlier but with the number of libraries I wanted access to with this Gulp setup, it would still puke. I worked around it using Bower and `path` to create a constant:

    var path  = require('path');
    const SASS_INCLUDE_PATHS = [
        path.join(__dirname, 'bower_components/normalize-scss'),
        path.join(__dirname, 'bower_components/susy/sass'),
        path.join(__dirname, 'bower_components/sassline/assets/sass'),
        path.join(__dirname, 'bower_components/megatype')
    ];

But I would much rather use NPM since Bower is apparently on its way out and Webpack seems like overkill :). This can be marked as closed.

**Comment by jgerigmeyer** [comment]
Hm, I would think the same `path` trick would work with `node_modules/`, regardless of the number of dependencies? ¯\_(ツ)_/¯
