### ISSUE TITLE
Susy 2 : 1200px container and 12 columns but debug image has extra column space

### ISSUE THREAD

**Issue by monolux** [oddbird/susy#662]
**Susy 2**

Please have a look at [https://www.sassmeister.com/gist/39b8136d4dcc6b8acfd269f675c97af5](https://www.sassmeister.com/gist/39b8136d4dcc6b8acfd269f675c97af5) and let me know what I am doing wrong to have the extra darker blue tiny bit of a column showing up when I select 3, 7, and 9 columns but especially visible **when I select 12 columns**. Where is that extra space coming from?

1200 / 12 = 100, so each column should be 100px wide and on a screen with 1600px width the 12 columns should display fine without any extra bit, no?

What really confuses me is that the extra bit shows up with 12, 13 and 14 columns selected, but not with 15 or 16 columns.

1200 / 12 = 100
1200 / 13 = 92.30769230769231
1200 / 14 = 85.71428571428571
1200 / 15 = 80
1200 / 16 = 75

So I assume if the result of the division is not a full number the debug image will have extra bits and when the result of the division is a full number the debug image won't have extra bits.

So why then does it have extra bits when I have a container of 1200px and 12 columns selected, that should be 100px per column and no extra bit. This also happens when using 3 columns, but 1200 / 3 = 400, so each column should have 400px and no extra bit, right?

Yes, in the [documentation](https://media.readthedocs.org/pdf/susy/latest/susy.pdf) on page 14 it says the debug image is not exact, however I don't think this is the issue here as the extra bit that gets added to the debug image on the very right hand side varies in size, meaning it is being calculated to show extra space as opposed to being off by several pixels.

How can I have the debug image display without extra bits on the far right hand side when using a 1200px wide container and 12 columns please? I don't like to have gutters, so included gutters: 0 as well as gutter-position: inside in the susy options.

Important addition, is the debug image affected by the vertical scrollbar when content goes under the fold and hence making the body narrower by the width of the scrollbar?

I also read [this post from Zell about the debug image](https://zellwk.com/blog/susy-grid-background-image/) but that does not seem to help me with the extra bit that gets added.

Thank you for any guidance helping me understand better what is going on here.

![susy-extra-space-debug-image-001](https://user-images.githubusercontent.com/5672418/31413567-2d80a8c0-ae1a-11e7-8a2a-94aed8ffbd08.png)

**Comment by monolux** [comment]
Just checked the Sassmeister in Firefox latest version and there the extra bit is not there and the debug image shows 100% correct. What in Chrome is causing this and does Susy 2 have a fix for Chrome or something I could add as a mixin that would take care of this in Chrome latest version? Normally I stand by Chrome and it looks like this is an exception to the rule where Chrome renders things incorrect.

**Comment by mirisuzanne** [comment]
This is the usual subpixel error that we warn about. If you resize the container, you should see that it jumps into place every X pixels, where X is roughly the number of columns. The errors stacks up for each column in the grid, adding 1px per column. So the more columns you add, the larger your potential error will be.

**Comment by mirisuzanne** [comment]
I'm glad to hear that Firefox has fixed the issue! Susy3 has also resolved it by moving to an SVG-image solution, rather than using background images.

**Comment by monolux** [comment]
**Crazy that Chrome is still doing this in late 2017!!**

Is there a way to use the Susy 3 SVG-image solution in Susy 2?
That would be fantastic!!

**Comment by mirisuzanne** [comment]
It's absolutely possible – but probably not straight-forward for the full range of options in Susy2. That's not going to be a high priority on my end.

But, you may be able to get it working for what you need. Take a look at the code in Susy3, and you'll see how we do it – creating a rectangle for each column, and positioning them with the core Susy functions.
