### ISSUE TITLE
upgrade from 2.2.12

### ISSUE THREAD

**Issue by amadhav1** [oddbird/susy#666]
Hello,

I upgraded from 2.2.12 to 3 for my project, and when I try and use container(75%) it no longer works.  what is an alternative for container() for Susy 3?  

Thanks,

Aaron

**Comment by mirisuzanne** [comment]
Susy3 is a major upgrade with breaking changes. For example, there are **no mixins** anywhere in Susy3. See our [introductory post](http://oddbird.net/2017/06/28/susy3/) for more details.
