### ISSUE TITLE
Guide to use Susy3 + Node.js + Gulp ?

### ISSUE THREAD

**Issue by webmasterpf** [oddbird/susy#667]
Hi,
I actually use Susy2 with the two others via GulpSass.
I would to use Susy 3 in the same context, 
To my mind, I need to get the new npm susy package which is in V3.
https://www.npmjs.com/package/susy

And so on, do I miss other changes to upgrade my settings ?

thanks

**Comment by webmasterpf** [comment]
So I begun.And I get my first error on compile:
```
 [susy-parse] Unknown shorthand property: [number] `1`
        on line 43 of node_modules/susy/sass/susy/_utilities.scss

```
I use Gulp, these are my settings:
`basePaths.node_modules +  'susy/sass/susy',`
In app.scss:
`@import '../node_modules/susy/sass/susy'; `

In my project I have 2 separates folders like : sass folder and node_modules folder at the same level.

thanks

**Comment by webmasterpf** [comment]
Do this could allow to reuse Susy2 syntax ?
https://codepen.io/mirisuzanne/pen/VWzwXj

**Comment by mirisuzanne** [comment]
Yes, Susy 3 is a major change to the syntax. This isn't a gulp issue. You'll have to update how you use Susy if you want to move to Susy3. It is also perfectly fine to keep projects on Susy2 if you prefer.

Those linked mixins will get you part way to Susy2 syntax - but not the whole way. They still expect Susy3 configuration (e.g. `susy-repeat(12)` instead of `12`) and they don't handle all the variations of `gutter-position` - you'd have to build that in (or set it up for the one you like).

I updated the [Susy docs](http://oddbird.net/susy/docs/) to include the changelog, and you can also read the [introduction articles](http://oddbird.net/susy/articles/) for more detail on using Susy3.

**Comment by robsonsobral** [comment]
@webmasterpf , npm follows [SemVer](http://semver.org/), which implies that major versions break things.

**Comment by webmasterpf** [comment]
So I test another thing like that: 
```
 .middle-content{
            width: susy-repeat( 12 of $desktopcol);         

        }
```
but I have an issue with my context definition I guess:
`$desktopcol: susy-repeat(12);`

```
Error: 12 of 1 1 1 1 1 1 1 1 1 1 1 1 is not an integer.
        on line 38 of sass/layout/_layout-bp-desktop.scss
>>             width: susy-repeat( 12 of $desktopcol);         
   --------------------------------^
```

**Comment by webmasterpf** [comment]
Anothers tests with strange reaction:
this `width: susy-repeat( 10 of 12);`  produce  ```
sass/content-type-style/_frontpage-style.scss
Error: 10 of 12 is not an integer.
        on line 17 of sass/content-type-style/_frontpage-style.scss
>>          width: susy-repeat( 10 of 12); 
```
this  ` width: susy-repeat( 12 of $desktopcol); ` produce 
```
 sass/content-type-style/_frontpage-style.scss
Error: 12 of 1 1 1 1 1 1 1 1 1 1 1 1 is not an integer.
        on line 17 of sass/content-type-style/_frontpage-style.scss
>>          width: susy-repeat( 12 of $desktopcol); 
```
and this `width: span(10 of 12);` produce no error, but no changes too in css...

**Comment by webmasterpf** [comment]
great I found the way, but I don't how 0_o
```
  width: span(10 of $desktopcol);
            padding:0, span(1),0,span(1);
```
produce:
```
    width: calc(5em + ((100% - 6em) / 12 * 10));
    padding: 0,calc(.5em + ((100% - 6em) / 12 * 1)),0,calc(.5em + ((100% - 6em) / 12 * 1));
```
but it seem not to be possible to set padding top, right,left etc..with this short css way. doesn"t it ?

**Comment by mirisuzanne** [comment]
I don't know what `$desktopcol` is, but I'd guess it's `susy-repeat(12)`?

- `susy-repeat()` is a way of [describing the columns setting](http://oddbird.net/susy/docs/config.html#function--susy-repeat). It does not take an argument like `x of y`, and should not be used on a property like `width`. It should only be used for the `columns` configuration.
-  `width: span(10 of 12)` is a correct usage, and should output CSS. Are you sure there is no output? I don't see how that could happen without an error.
- The CSS `padding` property takes a space-delimited list, not comma-delimited. Remove the commas and it will work.

**Comment by webmasterpf** [comment]
1- this is my setting : `$desktopcol: susy-repeat(12);`
2- finally,there is an output as I said in my last post
3- I did a mistake because so I fix this syntax error.

In addition, searching in doc work, and it will hepl me more efficiently 👍

**Comment by mirisuzanne** [comment]
There would be various ways to make video size to a container, but I wouldn't use Susy for that. `width: 100%` would get you part way there. Or, people often position videos absolutely in a sized container, with `0` for all `top`, `bottom`, `right`, `left` properties.

**Comment by webmasterpf** [comment]
Thanks, I will test.
