### ISSUE TITLE
Which way to build a gallery ?

### ISSUE THREAD

**Issue by webmasterpf** [oddbird/susy#671]
Hi,
after #667 ; I would to build a gallery layout based on a list like : 
```
<ul>
<li></li>
<li></li>
<li></li>
</ul>

```
Actually I'm using this css: 
```
li{
   margin: span(0.1);
   float: left;
   min-width: span(1);//not efficient
}
```

but if I add an item to the list , it doesn't go on a new line, so can I set a number of column with Susy3 like I done with Susy2 ?

Thanks

**Comment by mirisuzanne** [comment]
See #648 

That includes, from the bottom of the thread: 
- The Grid solution (simplest and most powerful, for most *modern* browsers)
- The Flexbox solution (still browser-driven, very good browser support)
- How to rebuild the Susy2 Float solution (less powerful, less flexible, more code)

**Comment by webmasterpf** [comment]
thanks
