### ISSUE TITLE
gutter() errors when used with asymmetrical grid created with susy-repeat()

### ISSUE THREAD

**Issue by marzelin** [oddbird/susy#676]
susy version: **3.0.3**

## what happens
this code:
```scss
$susy: (
  "columns": 150px susy-repeat(2),
);

.box {
  float: left;
  margin-right: gutter();
}
```
throws an error:
```
Error: [susy-parse] Unknown shorthand property: [list] `1 1`
        on line 43 of node_modules/susy/sass/susy/_utilities.scss
>>   @error '[#{$source}] #{$message}';
```

The error is not present when the grid is constructed without `susy-repeat()`
```scss
$susy: (
  "columns": 150px 1 1,
);
```

reproduction:
https://codesandbox.io/s/48z8w6po49

**Comment by mirisuzanne** [comment]
This should be fixed in 3.0.4 - just released. Let me know if you still have issues.

**Comment by mirisuzanne** [comment]
oops, of course! Try 3.0.5 :)

**Comment by marzelin** [comment]
works like a charm, thanks!

**Comment by mirisuzanne** [comment]
great!
