### ISSUE TITLE
No mixin named susy-breakpoint

### ISSUE THREAD

**Issue by keqhash** [oddbird/susy#682]
After Upgrading susy from 2.2.12 to 3.0.5 I am getting below error:

`No mixin named susy-breakpoint`

Full error:

```
ERROR in ./app/native/onboarding/index.scss
(./node_modules/css-loader??ref--6-1!./node_modules/postcss-loader/lib??ref--6-
2!./node_modules/@epegzz/sass-vars-loader/dist/sassVarsLoader.js??ref--6-3!./node_modules
/sass-loader/lib/loader.js!./app/native/onboarding/index.scss)
        Module build failed (from ./node_modules/sass-loader/lib/loader.js):

        undefined
                ^
              No mixin named susy-breakpoint

        Backtrace:
                node_modules/progressive-web-sdk/dist/components/grid/_base.scss:108
              in xxx\node_modules\progressive-web-sdk\dist\components\grid\_base.scss (line 108, column 10)

```

**Comment by mirisuzanne** [comment]
That's right. Susy 3 is a major upgrade, with major backwards-incompatible changes.

You can read the docs (and changelog): oddbird.net/susy/docs/
We also have several articles about Susy 3: oddbird.net/susy/articles/
Or you can lock into Susy 2 - there is no need to upgrade if you aren’t interested.

**Comment by keqhash** [comment]
Thank you very much.
The docs and articles were very useful.
I solved the issue by defining the missing mixins in my code and every thing went correctly after fixing some tweaks.

**Much appreciated** :+1: :1st_place_medal:
