### ISSUE TITLE
Pull mixin does not work it sems...

### ISSUE THREAD

**Issue by dimicdragan** [oddbird/susy#684]
On the oddbird.net website, solution was given on how to create `grid pull` - that is to calculate negative margins on the grid. It goes like this :

> We also override those options when pushing, pulling, padding, and bleeding:
`.pull-3 {
  margin-left: 0 - span(3 wide);
}`
>
however this prints out a not valid CSS: 
`margin: 0 - calc(3px - 8.333%)`
My guess is that it is because i use mixed units - so the calc prints out the whole calc expression instead of a single value.

Could you please post a valid mixin for `grid-pull` calculation. 
Much appreciated.

**Comment by dimicdragan** [comment]
I got a very quick response from Susanne. So i am posting it here, as agreed with her so it can benefit everyone.
`margin-left: calc(#{span(3 wide)} * -1)`
Thank you Susanne, much appreciated :-)

**Comment by xdebbie** [comment]
@dimicdragan , how is it going with Susy in 2020? I like to use 20+ columns and I am currently using my own grid system and I have been wondering whether the switch is worth.

**Comment by dimicdragan** [comment]
@xdebbie From my own experience - better to use flex or grid - however - if you have to stick to IE11 (like i do) - then you have to do your layout as floats, and keep flex (on the inner components) to very simple initial specs (in IE). That is why i decide to use Sussy3.0.
So far no regrets. You do have to create a few SCSS mixins initially, but then it works like a charm. Sussy is totally transparent - it only calculates and you set the calc on the BEM selectors for the components directly - so you have no grid classes anywhere in the code. Just awesome for me. I guess your choice will depend on what you need in reality... how complex your grid is, and so on...
