### ISSUE TITLE
inline-block version

### ISSUE THREAD

**Issue by 144288** [oddbird/susy#69]
What do you think about the grids that are going with inline-blocks? Seems like there are some cool advantages over using float. 

Could that work with susy?

**Comment by krazyjakee** [comment]
Hope nobody minds me leaving this here, but here is a solution to fix heights in javascript since that seems to be the only option for responsive, floated grids.

(Requires jQuery but is easily ported to vanilla)

```javascript
var gridCells = $(".grid-cells");
gridCells.height(Math.max.apply(null, gridCells.map(function() {
  return $(this).height();
}).get()));
```

Any other solutions/corrections welcome.

**Comment by ShadyMind** [comment]
I wrote a little [example ](http://s.codepen.io/ShadyMind/debug/rLYRWx) for inline-block layout at codepen
